zip_keys:
  -
    - python
    - numpy
    - python_impl

python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.5.* *_cpython
  - 3.6.* *_cpython
  - 3.7.* *_cpython
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  # - 3.10.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  # we build for the oldest version possible of numpy for forward compatibility
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.20
  - 1.20
  - 1.20
  - 1.20
  - 1.21

